# CHANGE THIS TO YOUR OWN DATASET
TTS_dataset: "MbankAI/Timur-neutral"

model_name: "canopylabs/orpheus-3b-0.1-ft"

# Training Args
epochs: 200
batch_size: 2
number_processes: 1
pad_token: 128263
save_steps: 50
learning_rate: 5.0e-5

# Naming and paths
save_folder: "ft-checkpoints"
project_name: "tuning-orpheus"
run_name: "5e5-0"
