DATASET: "MbankAI/Orpheus-tokenised-dataset"
MODEL_NAME: "canopylabs/orpheus-3b-0.1-ft"
OUTPUT_DIR: "finetuned_model"
KEEP_LAST_N_CHECKPOINTS: 5
LOGGING_STEPS: 50
SAVE_STEPS: 200
NUM_EPOCHS: 10
BATCH_SIZE: 4
GRADIENT_ACCUMULATION_STEPS: 32
GRADIENT_CHECKPOINTING: True
LEARNING_RATE: 1e-5
SEED: 42

LORA_RANK: 32
LORA_ALPHA: 64
LORA_DROPOUT: 0.05

PAD_TOKEN: 128263
