MANIFEST: DUMMY1/filtered_manifest.txt
MAX_AUDIO_FILES: 0
OUTPUT_DIR: "finetuned_model"
KEEP_LAST_N_CHECKPOINTS: 5
LOGGING_STEPS: 10
SAVE_STEPS: 50
NUM_EPOCHS: 10
BATCH_SIZE: 1
GRADIENT_ACCUMULATION_STEPS: 32
GRADIENT_CHECKPOINTING: False
LEARNING_RATE: 1e-5
SEED: 42
MODEL_NAME: "canopylabs/orpheus-3b-0.1-ft"
